/**
  ******************************************************************************
  * @file           : gpio.c
  * @brief          : GPIO Initialization and Configuration
  * @date           : {{ now().strftime('%b %d, %Y') }}
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#include "gpio.h"

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  /* GPIO Ports Clock Enable */
{% for gpio in gpio_config %}
  __HAL_RCC_{{ gpio.port }}_CLK_ENABLE();
{% endfor %}

{% for gpio in gpio_config %}
  /*Configure GPIO pin : {{ gpio.name }} */
  GPIO_InitStruct.Pin = GPIO_PIN_{{ gpio.pin }};
  GPIO_InitStruct.Mode = GPIO_MODE_{{ gpio.mode }};
{% if gpio.pull %}
  GPIO_InitStruct.Pull = GPIO_{{ gpio.pull }};
{% endif %}
{% if gpio.speed %}
  GPIO_InitStruct.Speed = GPIO_SPEED_{{ gpio.speed }};
{% endif %}
{% if gpio.alternate %}
  GPIO_InitStruct.Alternate = GPIO_{{ gpio.alternate }};
{% endif %}
  HAL_GPIO_Init({{ gpio.port }}, &GPIO_InitStruct);

{% endfor %}
}