
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  * @date           : {{ now().strftime('%b %d, %Y') }}
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */


/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>

{# Conditionally include peripheral headers if they have been configured #}
{% if gpio_example_needed %}#include "gpio.h"{% endif %}
{% if i2c_example_needed %}#include "i2c.h"{% endif %}
{% if uart_example_needed %}#include "uart.h"{% endif %}
{% if preset_example_needed %}#include "presets_in.h"
#include "presets_out.h"{% endif %}


/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);

{# Generate prototypes for example tasks if they will be created #}
{% if preset_example_needed %}void Presets_Init(void);
void Presets_Process(void);{% endif %}
{% if gpio_example_needed %}static void GPIO_Example_Task(void);{% endif %}
{% if i2c_example_needed %}static void I2C_Example_Task(void);{% endif %}
{% if uart_example_needed %}static void UART_Example_Task(void);{% endif %}


/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
  {% if gpio_configs %}MX_GPIO_Init();{% endif %}
  {% if i2c_interfaces %}MX_I2C_Init();{% endif %}
  {% if uart_interfaces %}MX_UART_Init();{% endif %}

  {% if preset_example_needed %}
  // Initialize presets based on configuration
  Presets_Init();
  {% endif %}

  /* Infinite loop */
  while (1)
  {
    {% if preset_example_needed %}
    Presets_Process();
    {% endif %}
    {% if gpio_example_needed and not preset_example_needed %}
    GPIO_Example_Task();
    {% endif %}
    {% if i2c_example_needed and not preset_example_needed %}
    I2C_Example_Task();
    {% endif %}
    {% if uart_example_needed and not preset_example_needed %}
    UART_Example_Task();
    {% endif %}
  }
}

/**
  * @brief System Clock Configuration for STM32G4 series.
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = RCC_PLLM_DIV4;
  RCC_OscInitStruct.PLL.PLLN = 32;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

/* USER CODE BEGIN 4 */

{% if preset_example_needed %}
/**
  * @brief  Initialize presets based on configuration
  * @retval None
  */
void Presets_Init(void)
{
  {% for case in preset_cases %}
  // Initialize: {{ case.get("input_key", "Unknown input") }} -> {{ case.get("output_key", "Unknown output") }}
  {% if case.input_type == "gy521" %}
  // GY-521 (MPU6050) initialization
  // Will initialize in Presets_Process()
  {% elif case.input_type == "dht11" %}
  // DHT11 initialization
  // GPIO pin already configured in MX_GPIO_Init()
  {% elif case.input_type == "potentiometer" %}
  // ADC initialization for potentiometer
  // ADC already configured in CubeMX
  {% endif %}
  
  {% if case.output_type == "lcd" %}
  // LCD initialization
  LCD_Init();
  LCD_Clear();
  {% elif case.output_type == "uart" %}
  // UART already initialized in MX_UART_Init()
  {% elif case.output_type == "pwm" %}
  // PWM timer already initialized in CubeMX
  {% endif %}
  {% endfor %}
}

/**
  * @brief  Process presets: read input, apply formula, check threshold, set output
  * @retval None
  */
void Presets_Process(void)
{
  {% for case in preset_cases %}
  // ========== Preset: {{ case.get("input_key", "Unknown") }} -> {{ case.get("output_key", "Unknown") }} ==========
  
  {% if case.input_type == "gy521" %}
  // Read GY-521 (MPU6050) accelerometer data
  float accel_x = 0.0f, accel_y = 0.0f, accel_z = 0.0f;
    MPU6050_Read_Accel(&accel_x, &accel_y, &accel_z);
  
  // Calculate magnitude
  float magnitude = sqrt(accel_x * accel_x + accel_y * accel_y + accel_z * accel_z);
  {% if case.get("processing", {}).get("enabled") %}
  // Apply formula: {{ case.get("processing", {}).get("formula", "") }}
  float processed_value = magnitude {{ case.get("processing", {}).get("formula", "") }};
  {% else %}
  float processed_value = magnitude;  // Use raw magnitude
  {% endif %}
  
  {% elif case.input_type == "potentiometer" %}
  // Read potentiometer value via ADC
  uint16_t raw_value = 0;
  if (POT_ReadRaw(&hadc1, ADC_CHANNEL_0, &raw_value) == HAL_OK)
  {
    float value = POT_RawToRatio(raw_value);  // Convert to 0.0-1.0 ratio
    {% if case.get("processing", {}).get("enabled") %}
    // Apply formula: {{ case.get("processing", {}).get("formula", "") }}
    float processed_value = value {{ case.get("processing", {}).get("formula", "") }};
    {% else %}
    float processed_value = value * 1000.0f;  // Default: scale to 0-1000
    {% endif %}
    
  {% elif case.input_type == "digital_in" %}
  // Read digital input
  uint8_t din_value = HAL_GPIO_ReadPin(DIN_GPIO_Port, DIN_Pin);
  float processed_value = din_value ? 1.0f : 0.0f;
  
  {% elif case.input_type == "dht11" %}
  // Read DHT11 sensor
  DHT11_Data_t dht_data;
  if (DHT11_Read(&dht_data) == HAL_OK)
  {
    float processed_value = dht_data.temperature;  // Use temperature
    {% if case.get("processing", {}).get("enabled") %}
    // Apply formula: {{ case.get("processing", {}).get("formula", "") }}
    processed_value = processed_value {{ case.get("processing", {}).get("formula", "") }};
    {% endif %}
  
  {% elif case.input_type == "ky013" %}
  // Read KY-013 temperature sensor via ADC
  uint16_t raw_temp = 0;
  if (KY013_ReadTemp(&hadc1, &raw_temp) == HAL_OK)
  {
    float processed_value = KY013_TempConversion(raw_temp);
    {% if case.get("processing", {}).get("enabled") %}
    // Apply formula: {{ case.get("processing", {}).get("formula", "") }}
    processed_value = processed_value {{ case.get("processing", {}).get("formula", "") }};
    {% endif %}
  
  {% endif %}
  
  // Process the output based on threshold
  {% if case.get("threshold", {}).get("enabled") %}
  uint16_t threshold = {{ case.get("threshold", {}).get("value", "1000") }};
  bool should_activate = processed_value > threshold;
  {% else %}
  bool should_activate = processed_value > 0.5f;  // Default threshold
  {% endif %}
  
  // Close the input reading block for sensors that needed it
  {% if case.input_type == "potentiometer" or case.input_type == "dht11" or case.input_type == "ky013" %}
  }
  {% endif %}
  
  // Process output based on type
  {% if case.output_type == "lcd" %}
  // Display on LCD
  if (should_activate)
  {
    LCD_SendString("ACTIVE: VALUE");
    // You can use sprintf to format the value
  }
  else
  {
    LCD_SendString("INACTIVE    ");
  }
  
  {% elif case.output_type == "uart" %}
  // Send via UART
  if (should_activate)
  {
    uint8_t msg[] = "ACTIVE\r\n";
    UART_Transmit(&huart1, msg, sizeof(msg) - 1, 100);
  }
  
  {% elif case.output_type == "pwm" %}
  // Set PWM duty cycle
  if (should_activate)
  {
    uint16_t duty = (uint16_t)(processed_value * 1000);  // Scale to PWM range
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1, duty);
  }
  else
  {
    __HAL_TIM_SET_COMPARE(&htim1, TIM_CHANNEL_1, 0);
  }
  
  {% elif case.output_type == "digital_out" %}
  // Set digital output (LED)
  if (should_activate)
  {
    HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_SET);
  }
  else
  {
    HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_RESET);
  }
  
  {% endif %}
  
  {% endfor %}
  
  HAL_Delay(100);  // Loop delay
}
{% endif %}

/* USER CODE BEGIN 4 (Old examples) */
{% if gpio_example_needed %}
/**
  * @brief  A simple task demonstrating GPIO input and output.
  * @retval None
  */
static void GPIO_Example_Task(void)
{
    {# Generate a more complex example if both input and output are defined #}
    {% if first_gpio_input and first_gpio_output %}
    // Reads the state of the input pin and sets the output pin accordingly.
    if (HAL_GPIO_ReadPin({{ first_gpio_input.name }}_GPIO_Port, {{ first_gpio_input.name }}_Pin) == GPIO_PIN_SET)
    {
        HAL_GPIO_WritePin({{ first_gpio_output.name }}_GPIO_Port, {{ first_gpio_output.name }}_Pin, GPIO_PIN_SET);
    }
    else
    {
        HAL_GPIO_WritePin({{ first_gpio_output.name }}_GPIO_Port, {{ first_gpio_output.name }}_Pin, GPIO_PIN_RESET);
    }
    {% elif first_gpio_output %}
    // Toggles the first configured output pin every 500ms.
    HAL_GPIO_TogglePin({{ first_gpio_output.name }}_GPIO_Port, {{ first_gpio_output.name }}_Pin);
    HAL_Delay(500);
    {% endif %}
}
{% endif %}

{% if i2c_example_needed %}
/**
  * @brief  A simple task demonstrating I2C master communication.
  * @retval None
  */
static void I2C_Example_Task(void)
{
    // Attempts to write a counter value to register 0x01 of the first configured I2C slave device.
    // This is a common pattern for configuring sensors.
    static uint8_t counter = 0;
    HAL_StatusTypeDef status = I2C_Write_Register(&hi2c{{ i2c_interfaces[0].num }}, {{ i2c_interfaces[0].devices[0].name }}_ADDR, 0x01, counter++);
    
    if (status == HAL_OK)
    {
      // Communication successful
    }
    else
    {
      // Communication failed
    }

    HAL_Delay(1000); // Wait 1 second before the next transmission
}
{% endif %}

{% if uart_example_needed %}
/**
  * @brief  A simple task demonstrating UART transmission.
  * @retval None
  */
static void UART_Example_Task(void)
{
    uint8_t msg[] = "Hello from STM32!\r\n";
    
    // Transmit the message via the first configured UART interface.
    // The generated UART_Transmit function handles the selected transfer mode (Polling, IT, or DMA).
    UART_Transmit(&huart{{ uart_interfaces[0].num }}, msg, sizeof(msg) - 1, 100);
    
    HAL_Delay(1000); // Wait 1 second before the next transmission
}
{% endif %}
/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

