/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  * @date           : {{ now().strftime('%b %d, %Y') }}
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */
/* USER CODE END Header */

/* Includes ------------------------------------------------------------------*/
#include "main.h"

{# Conditionally include peripheral headers if they have been configured #}
{% if gpio_example_needed %}#include "gpio.h"{% endif %}
{% if i2c_example_needed %}#include "i2c.h"{% endif %}
{% if uart_example_needed %}#include "uart.h"{% endif %}


/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);

{# Generate prototypes for example tasks if they will be created #}
{% if gpio_example_needed %}static void GPIO_Example_Task(void);{% endif %}
{% if i2c_example_needed %}static void I2C_Example_Task(void);{% endif %}
{% if uart_example_needed %}static void UART_Example_Task(void);{% endif %}


/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
  {% if gpio_configs %}MX_GPIO_Init();{% endif %}
  {% if i2c_interfaces %}MX_I2C_Init();{% endif %}
  {% if uart_interfaces %}MX_UART_Init();{% endif %}

  /* Infinite loop */
  while (1)
  {
    {% if gpio_example_needed %}
    GPIO_Example_Task();
    {% endif %}
    {% if i2c_example_needed %}
    I2C_Example_Task();
    {% endif %}
    {% if uart_example_needed %}
    UART_Example_Task();
    {% endif %}
  }
}

/**
  * @brief System Clock Configuration for STM32G4 series.
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = RCC_PLLM_DIV4;
  RCC_OscInitStruct.PLL.PLLN = 32;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

/* USER CODE BEGIN 4 */
{% if gpio_example_needed %}
/**
  * @brief  A simple task demonstrating GPIO input and output.
  * @retval None
  */
static void GPIO_Example_Task(void)
{
    {# Generate a more complex example if both input and output are defined #}
    {% if first_gpio_input and first_gpio_output %}
    // Reads the state of the input pin and sets the output pin accordingly.
    if (HAL_GPIO_ReadPin({{ first_gpio_input.name }}_GPIO_Port, {{ first_gpio_input.name }}_Pin) == GPIO_PIN_SET)
    {
        HAL_GPIO_WritePin({{ first_gpio_output.name }}_GPIO_Port, {{ first_gpio_output.name }}_Pin, GPIO_PIN_SET);
    }
    else
    {
        HAL_GPIO_WritePin({{ first_gpio_output.name }}_GPIO_Port, {{ first_gpio_output.name }}_Pin, GPIO_PIN_RESET);
    }
    {% elif first_gpio_output %}
    // Toggles the first configured output pin every 500ms.
    HAL_GPIO_TogglePin({{ first_gpio_output.name }}_GPIO_Port, {{ first_gpio_output.name }}_Pin);
    HAL_Delay(500);
    {% endif %}
}
{% endif %}

{% if i2c_example_needed %}
/**
  * @brief  A simple task demonstrating I2C master communication.
  * @retval None
  */
static void I2C_Example_Task(void)
{
    // Attempts to write a counter value to register 0x01 of the first configured I2C slave device.
    // This is a common pattern for configuring sensors.
    static uint8_t counter = 0;
    HAL_StatusTypeDef status = I2C_Write_Register(&hi2c{{ i2c_interfaces[0].num }}, {{ i2c_interfaces[0].devices[0].name }}_ADDR, 0x01, counter++);
    
    if (status == HAL_OK)
    {
      // Communication successful
    }
    else
    {
      // Communication failed
    }

    HAL_Delay(1000); // Wait 1 second before the next transmission
}
{% endif %}

{% if uart_example_needed %}
/**
  * @brief  A simple task demonstrating UART transmission.
  * @retval None
  */
static void UART_Example_Task(void)
{
    uint8_t msg[] = "Hello from STM32!\r\n";
    
    // Transmit the message via the first configured UART interface.
    // The generated UART_Transmit function handles the selected transfer mode (Polling, IT, or DMA).
    UART_Transmit(&huart{{ uart_interfaces[0].num }}, msg, sizeof(msg) - 1, 100);
    
    HAL_Delay(1000); // Wait 1 second before the next transmission
}
{% endif %}
/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}

