/**
  ******************************************************************************
  * @file           : presets_out.c
  * @brief          : Preset Output Actuator Functions
  * @date           : {{ now().strftime('%b %d, %Y') }}
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#include "presets_out.h"

{% if OUT.lcd or i2c_handle %}extern I2C_HandleTypeDef {{ i2c_handle if i2c_handle else 'hi2c1' }};{% endif %}
{% if OUT.uart or uart_handle %}extern UART_HandleTypeDef {{ uart_handle if uart_handle else 'huart1' }};{% endif %}
{% if OUT.pwm or tim_handle %}extern TIM_HandleTypeDef  {{ tim_handle if tim_handle else 'htim1' }};{% endif %}

{% if OUT.lcd %}
#define LCD_ADDR {{ lcd_addr if lcd_addr else '0x4E' }}

static void lcd_send_cmd(uint8_t cmd)
{
    uint8_t u = (cmd & 0xF0);
    uint8_t l = (cmd << 4) & 0xF0;
    uint8_t t[4] = { u|0x0C, u|0x08, l|0x0C, l|0x08 };
    HAL_I2C_Master_Transmit(&{{ i2c_handle if i2c_handle else 'hi2c1' }}, LCD_ADDR, t, 4, 100);
}

static void lcd_send_data(uint8_t data)
{
    uint8_t u = (data & 0xF0);
    uint8_t l = (data << 4) & 0xF0;
    uint8_t t[4] = { u|0x0D, u|0x09, l|0x0D, l|0x09 };
    HAL_I2C_Master_Transmit(&{{ i2c_handle if i2c_handle else 'hi2c1' }}, LCD_ADDR, t, 4, 100);
}

void LCD_Clear(void) { lcd_send_cmd(0x01); HAL_Delay(2); }

void LCD_Init(void)
{
    HAL_Delay(50);
    lcd_send_cmd(0x30); HAL_Delay(5);
    lcd_send_cmd(0x30); HAL_Delay(1);
    lcd_send_cmd(0x30); HAL_Delay(1);
    lcd_send_cmd(0x20); HAL_Delay(1);
    lcd_send_cmd(0x28); HAL_Delay(1);
    lcd_send_cmd(0x08); HAL_Delay(1);
    LCD_Clear();
    lcd_send_cmd(0x06); HAL_Delay(1);
    lcd_send_cmd(0x0C); HAL_Delay(1);
}

void LCD_SendString(const char *s)
{
    while (*s) lcd_send_data((uint8_t)*s++);
}

void LCD_SetCursor(uint8_t row, uint8_t col)
{
    uint8_t row_offsets[] = { 0x00, 0x40, 0x14, 0x54 };
    if (row >= 4) row = 0;
    lcd_send_cmd(0x80 | (col + row_offsets[row]));
}
{% endif %}

{% if OUT.uart %}
HAL_StatusTypeDef OUT_UART_Print(const char *s)
{
    const uint8_t *p = (const uint8_t*)s;
    return HAL_UART_Transmit(&{{ uart_handle if uart_handle else 'huart1' }}, (uint8_t*)p, (uint16_t)strlen(s), 100);
}
{% endif %}

{% if OUT.pwm %}
/* duty_0_1000: 0..1000 == 0..100% */
void PWM_Set(uint16_t duty_0_1000)
{
    if (duty_0_1000 > 1000) duty_0_1000 = 1000;
    __HAL_TIM_SET_COMPARE(&{{ tim_handle if tim_handle else 'htim1' }}, TIM_CHANNEL_1, duty_0_1000);
}
{% endif %}

{% if OUT.dout %}
void DOUT_Write(GPIO_TypeDef *port, uint16_t pin, GPIO_PinState s)
{
    HAL_GPIO_WritePin(port, pin, s);
}
{% endif %}
