/**
  ******************************************************************************
  * @file           : uart.c
  * @brief          : UART/USART Peripheral Configuration
  * @date           : {{ now().strftime('%b %d, %Y') }}
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#include "uart.h"

// --- Handles Declaration ---
{% for uart in uart_interfaces %}
UART_HandleTypeDef huart{{ uart.num }};
{% endfor %}

// --- MX_UART_Init Function ---
void MX_UART_Init(void)
{
{% for uart in uart_interfaces %}
    /* {{ uart.interface }} - Clock enable moved to HAL_UART_MspInit */

    huart{{ uart.num }}.Instance        = {{ uart.interface }};
    huart{{ uart.num }}.Init.BaudRate   = {{ uart.baud_rate }};
    huart{{ uart.num }}.Init.WordLength = {{ uart.word_length }};
    huart{{ uart.num }}.Init.StopBits   = {{ uart.stop_bits }};
    huart{{ uart.num }}.Init.Parity     = {{ uart.parity }};
    huart{{ uart.num }}.Init.Mode       = {{ uart.mode }};
    huart{{ uart.num }}.Init.HwFlowCtl  = {{ uart.hw_flow_ctl }};
    huart{{ uart.num }}.Init.OverSampling = {{ uart.oversampling }};
    huart{{ uart.num }}.Init.OneBitSampling = UART_ONE_BIT_SAMPLE_DISABLE;
    huart{{ uart.num }}.Init.ClockPrescaler = UART_PRESCALER_DIV1;
    huart{{ uart.num }}.AdvancedInit.AdvFeatureInit = UART_ADVFEATURE_NO_INIT;
    huart{{ uart.num }}.FifoMode = UART_FIFOMODE_DISABLE;

    if (HAL_UART_Init(&huart{{ uart.num }}) != HAL_OK)
    {
        Error_Handler();
    }
{% endfor %}
}

/* MSP: GPIO configuration for UART */
void HAL_UART_MspInit(UART_HandleTypeDef* uartHandle)
{
    GPIO_InitTypeDef GPIO_InitStruct = {0};
    
    if(uartHandle->Instance==USART2)
    {
        /* USART2 clock enable */
        __HAL_RCC_USART2_CLK_ENABLE();
        __HAL_RCC_GPIOA_CLK_ENABLE();
        
        /**USART2 GPIO Configuration    
        PA2     ------> USART2_TX
        PA3     ------> USART2_RX 
        */
        GPIO_InitStruct.Pin = GPIO_PIN_2|GPIO_PIN_3;
        GPIO_InitStruct.Mode = GPIO_MODE_AF_PP;
        GPIO_InitStruct.Pull = GPIO_NOPULL;
        GPIO_InitStruct.Speed = GPIO_SPEED_FREQ_LOW;
        GPIO_InitStruct.Alternate = GPIO_AF7_USART2;
        HAL_GPIO_Init(GPIOA, &GPIO_InitStruct);
    }
}

/*
 * ----------------------------------------------------------------
 * --- Application-level Transmit/Receive Functions ---
 * ----------------------------------------------------------------
 */
HAL_StatusTypeDef UART_Transmit(UART_HandleTypeDef *huart, uint8_t *data, uint16_t size, uint32_t timeout)
{
    {% for uart in uart_interfaces %}
    if (huart->Instance == {{ uart.interface }})
    {
        {% if uart.transferMode == 'POLLING' %}
        return HAL_UART_Transmit(huart, data, size, timeout);
        {% elif uart.transferMode == 'INTERRUPT' %}
        return HAL_UART_Transmit_IT(huart, data, size);
        {% elif uart.transferMode == 'DMA' %}
        return HAL_UART_Transmit_DMA(huart, data, size);
        {% else %}
        return HAL_UART_Transmit(huart, data, size, timeout);
        {% endif %}
    }
    {% endfor %}
    return HAL_ERROR;
}

HAL_StatusTypeDef UART_Receive(UART_HandleTypeDef *huart, uint8_t *buffer, uint16_t size, uint32_t timeout)
{
    {% for uart in uart_interfaces %}
    if (huart->Instance == {{ uart.interface }})
    {
        {% if uart.transferMode == 'POLLING' %}
        return HAL_UART_Receive(huart, buffer, size, timeout);
        {% elif uart.transferMode == 'INTERRUPT' %}
        return HAL_UART_Receive_IT(huart, buffer, size);
        {% elif uart.transferMode == 'DMA' %}
        return HAL_UART_Receive_DMA(huart, buffer, size);
        {% else %}
        return HAL_UART_Receive(huart, buffer, size, timeout);
        {% endif %}
    }
    {% endfor %}
    return HAL_ERROR;
}
