/**
  ******************************************************************************
  * @file           : gpio.c
  * @brief          : GPIO Initialization and Configuration
  * @date           : Oct 28, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#include "gpio.h"

/**
  * @brief GPIO Initialization Function
  * @param None
  * @retval None
  */
void MX_GPIO_Init(void)
{
  GPIO_InitTypeDef GPIO_InitStruct = {0};

  /* GPIO Ports Clock Enable */

}