
/**
  ******************************************************************************
  * @file           : main.c
  * @brief          : Main program body
  * @date           : Oct 30, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */


/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include <math.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#include "gpio.h"
#include "i2c.h"
#include "uart.h"
#include "presets_in.h"
#include "presets_out.h"


/* Private function prototypes -----------------------------------------------*/
void SystemClock_Config(void);

void Presets_Init(void);
void Presets_Process(void);


/**
  * @brief  The application entry point.
  * @retval int
  */
int main(void)
{
  /* MCU Configuration--------------------------------------------------------*/

  /* Reset of all peripherals, Initializes the Flash interface and the Systick. */
  HAL_Init();

  /* Configure the system clock */
  SystemClock_Config();

  /* Initialize all configured peripherals */
  MX_GPIO_Init();
  MX_I2C_Init();
  MX_UART_Init();

  // Initialize presets based on configuration
  Presets_Init();

  /* Infinite loop */
  while (1)
  {
    Presets_Process();
  }
}

/**
  * @brief System Clock Configuration for STM32G4 series.
  * @retval None
  */
void SystemClock_Config(void)
{
  RCC_OscInitTypeDef RCC_OscInitStruct = {0};
  RCC_ClkInitTypeDef RCC_ClkInitStruct = {0};

  /** Configure the main internal regulator output voltage
  */
  HAL_PWREx_ControlVoltageScaling(PWR_REGULATOR_VOLTAGE_SCALE1);

  /** Initializes the RCC Oscillators according to the specified parameters
  * in the RCC_OscInitTypeDef structure.
  */
  RCC_OscInitStruct.OscillatorType = RCC_OSCILLATORTYPE_HSI;
  RCC_OscInitStruct.HSIState = RCC_HSI_ON;
  RCC_OscInitStruct.HSICalibrationValue = RCC_HSICALIBRATION_DEFAULT;
  RCC_OscInitStruct.PLL.PLLState = RCC_PLL_ON;
  RCC_OscInitStruct.PLL.PLLSource = RCC_PLLSOURCE_HSI;
  RCC_OscInitStruct.PLL.PLLM = RCC_PLLM_DIV4;
  RCC_OscInitStruct.PLL.PLLN = 32;
  RCC_OscInitStruct.PLL.PLLP = RCC_PLLP_DIV2;
  RCC_OscInitStruct.PLL.PLLQ = RCC_PLLQ_DIV2;
  RCC_OscInitStruct.PLL.PLLR = RCC_PLLR_DIV2;
  if (HAL_RCC_OscConfig(&RCC_OscInitStruct) != HAL_OK)
  {
    Error_Handler();
  }

  /** Initializes the CPU, AHB and APB buses clocks
  */
  RCC_ClkInitStruct.ClockType = RCC_CLOCKTYPE_HCLK|RCC_CLOCKTYPE_SYSCLK
                              |RCC_CLOCKTYPE_PCLK1|RCC_CLOCKTYPE_PCLK2;
  RCC_ClkInitStruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
  RCC_ClkInitStruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
  RCC_ClkInitStruct.APB1CLKDivider = RCC_HCLK_DIV1;
  RCC_ClkInitStruct.APB2CLKDivider = RCC_HCLK_DIV1;

  if (HAL_RCC_ClockConfig(&RCC_ClkInitStruct, FLASH_LATENCY_2) != HAL_OK)
  {
    Error_Handler();
  }
}

/* USER CODE BEGIN 4 */

/**
  * @brief  Initialize presets based on configuration
  * @retval None
  */
void Presets_Init(void)
{
  
  
  
  
  
  // Initialize MPU6050
  MPU6050_Init();
  HAL_Delay(100);
  
  
  
  // UART already initialized in MX_UART_Init()
}

/**
  * @brief  Process presets: read input, apply formula, check threshold, set output
  * @retval None
  */
void Presets_Process(void)
{
  
  static uint32_t last_update = 0;
  char buffer[64];  // Buffer for UART/LCD text
  
  
  // Update display every 200ms
  if (HAL_GetTick() - last_update < 200) {
    return;
  }
  last_update = HAL_GetTick();
  
  // ========== Preset: GY-521 Sensor -> UART ==========
  
  // Read GY-521 (MPU6050) accelerometer data
  float accel_x = 0.0f, accel_y = 0.0f, accel_z = 0.0f;
  MPU6050_Read_Accel(&accel_x, &accel_y, &accel_z);
  
  // Calculate magnitude (for reference, not used with UART output)
  // float magnitude = sqrt(accel_x * accel_x + accel_y * accel_y + accel_z * accel_z);
  
  // Process output based on type
  // Send via UART
  // Send MPU6050 accelerometer data via UART
  // Convert floats to integers for transmission (ARM doesn't support %f by default)
  int16_t ax_int = (int16_t)(accel_x * 100.0f);
  int16_t ay_int = (int16_t)(accel_y * 100.0f);
  int16_t az_int = (int16_t)(accel_z * 100.0f);
  
  snprintf(buffer, sizeof(buffer), "X:%d.%02d Y:%d.%02d Z:%d.%02d\r\n", 
           ax_int/100, abs(ax_int%100),
           ay_int/100, abs(ay_int%100),
           az_int/100, abs(az_int%100));
  OUT_UART_Print(buffer);
  
  
  
  
}

/* USER CODE BEGIN 4 (Old examples) */


/* USER CODE END 4 */

/**
  * @brief  This function is executed in case of error occurrence.
  * @retval None
  */
void Error_Handler(void)
{
  /* USER CODE BEGIN Error_Handler_Debug */
  __disable_irq();
  while (1)
  {
  }
  /* USER CODE END Error_Handler_Debug */
}
