/**
  ******************************************************************************
  * @file           : presets_out.c
  * @brief          : Preset Output Actuator Functions
  * @date           : Oct 30, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#include "presets_out.h"
#include <string.h>

extern I2C_HandleTypeDef hi2c1;
extern UART_HandleTypeDef huart2;


HAL_StatusTypeDef OUT_UART_Print(const char *s)
{
    const uint8_t *p = (const uint8_t*)s;
    return HAL_UART_Transmit(&huart2, (uint8_t*)p, (uint16_t)strlen(s), 100);
}


