/**
  ******************************************************************************
  * @file           : presets_in.c
  * @brief          : Preset Input Sensor Functions
  * @date           : Nov 03, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#include "presets_in.h"





/* =========================
 *  Potentiometer (ADC)
 * ========================= */
HAL_StatusTypeDef POT_ReadRaw(ADC_HandleTypeDef* hadc, uint32_t channel, uint16_t* out_raw)
{
    if (!hadc || !out_raw) return HAL_ERROR;
    
    ADC_ChannelConfTypeDef sConfig = {0};
    sConfig.Channel = channel;
    sConfig.Rank = ADC_REGULAR_RANK_1;
    sConfig.SamplingTime = ADC_SAMPLETIME_47CYCLES_5;
    sConfig.SingleDiff = ADC_SINGLE_ENDED;
    sConfig.OffsetNumber = ADC_OFFSET_NONE;
    sConfig.Offset = 0;
    
    if (HAL_ADC_ConfigChannel(hadc, &sConfig) != HAL_OK) return HAL_ERROR;
    if (HAL_ADC_Start(hadc) != HAL_OK) return HAL_ERROR;
    if (HAL_ADC_PollForConversion(hadc, 10) != HAL_OK) return HAL_ERROR;
    *out_raw = (uint16_t)HAL_ADC_GetValue(hadc);
    HAL_ADC_Stop(hadc);
    return HAL_OK;
}
float POT_RawToRatio(uint16_t raw)
{
    return (float)raw / 4095.0f;
}
