/**
  ******************************************************************************
  * @file           : uart.c
  * @brief          : UART/USART Peripheral Configuration
  * @date           : Oct 30, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#include "uart.h"

// --- Handles Declaration ---
UART_HandleTypeDef huart2;

// --- MX_UART_Init Function ---
void MX_UART_Init(void)
{
    /* USART2 */
    __HAL_RCC_USART2_CLK_ENABLE();  // clock do PERIFÉRICO

    huart2.Instance        = USART2;
    huart2.Init.BaudRate   = 115200;
    huart2.Init.WordLength = UART_WORDLENGTH_8B;
    huart2.Init.StopBits   = UART_STOPBITS_1;
    huart2.Init.Parity     = UART_PARITY_NONE;
    huart2.Init.Mode       = UART_MODE_TX_RX;
    huart2.Init.HwFlowCtl  = UART_HWCONTROL_NONE;
    huart2.Init.OverSampling = UART_OVERSAMPLING_16;

    if (HAL_UART_Init(&huart2) != HAL_OK)
    {
        Error_Handler();
    }
}

/* MSP: NÃO configurar GPIO aqui (pinmux e __HAL_RCC_GPIOx_CLK_ENABLE ficam no gpio.c) */
void HAL_UART_MspInit(UART_HandleTypeDef* uartHandle)
{
    (void)uartHandle;
    /* Intencionalmente vazio. Se quiser NVIC/DMA, configure aqui. */
}

/*
 * ----------------------------------------------------------------
 * --- Application-level Transmit/Receive Functions ---
 * ----------------------------------------------------------------
 */
HAL_StatusTypeDef UART_Transmit(UART_HandleTypeDef *huart, uint8_t *data, uint16_t size, uint32_t timeout)
{
    if (huart->Instance == USART2)
    {
        return HAL_UART_Transmit(huart, data, size, timeout);
    }
    return HAL_ERROR;
}

HAL_StatusTypeDef UART_Receive(UART_HandleTypeDef *huart, uint8_t *buffer, uint16_t size, uint32_t timeout)
{
    if (huart->Instance == USART2)
    {
        return HAL_UART_Receive(huart, buffer, size, timeout);
    }
    return HAL_ERROR;
}