/**
  ******************************************************************************
  * @file           : adc.h
  * @brief          : Header for adc.c file. Contains ADC peripheral configurations.
  * @date           : {{ now().strftime('%b %d, %Y') }}
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */
/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __ADC_H__
#define __ADC_H__

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "main.h"
#include "stm32g4xx_hal_adc.h"

/* ADC Handle Declaration ----------------------------------------------------*/
extern ADC_HandleTypeDef hadc1;

/* Function Prototypes -------------------------------------------------------*/
void MX_ADC_Init(void);

#ifdef __cplusplus
}
#endif

#endif /* __ADC_H__ */

