/*
 * i2c.h
 *
 * Created on: {{ now().strftime('%b %d, %Y') }}
 * Author: Auto-generated by Config Tool
 */

#ifndef __I2C_H__
#define __I2C_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

/* --- I2C Handles (Extern Declaration) --- */
{% for i2c in i2c_interfaces %}
extern I2C_HandleTypeDef hi2c{{ i2c.num }};
{% endfor %}

/* --- I2C Slave Device Addresses --- */
{% for i2c in i2c_interfaces %}
{% if i2c.devices %}
/* Slave Addresses for I2C{{ i2c.num }} Bus */
{% for device in i2c.devices %}
#define {{ device.name }}_ADDR ({{ "0x%X"|format(device.address_hal) }}) 
{% endfor %}
{% endif %}
{% endfor %}

/* --- Function Prototypes --- */
void MX_I2C_Init(void);


#ifdef __cplusplus
}
#endif
#endif /* __I2C_H__ */