/* USER CODE BEGIN Header */
/**
  ******************************************************************************
  * @file           : main.h
  * @brief          : Header for main.c file.
  * This file contains the common defines of the application.
  * @date           : {{ now().strftime('%b %d, %Y') }}
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */
/* USER CODE END Header */

#ifndef __MAIN_H
#define __MAIN_H

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "stm32g4xx_hal.h" // Change this to your specific MCU series HAL header if needed

/* Exported functions prototypes ---------------------------------------------*/
void Error_Handler(void);

/* Private defines -----------------------------------------------------------*/

{# This is the most important part: Generate #defines for all configured pins #}
{% for pin in all_pins %}
#define {{ pin.name }}_Pin GPIO_PIN_{{ pin.pin }}
#define {{ pin.name }}_GPIO_Port {{ pin.port }}
{% endfor %}

#ifdef __cplusplus
}
#endif

#endif /* __MAIN_H */
