/**
  ******************************************************************************
  * @file           : presets_out.h
  * @brief          : Header for presets_out.c file. Contains preset output actuator function prototypes.
  * @date           : {{ now().strftime('%b %d, %Y') }}
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#ifndef __PRESETS_OUT_H__
#define __PRESETS_OUT_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"
{% if OUT.lcd %}
#include "i2c.h"
{% endif %}
{% if OUT.uart %}
#include "uart.h"
{% endif %}
{% if OUT.pwm %}
#include "stm32g4xx_hal_tim.h"
{% endif %}

{% if OUT.lcd %}
void LCD_Init(void);
void LCD_Clear(void);
void LCD_SendString(const char *s);
void LCD_SetCursor(uint8_t row, uint8_t col);
{% endif %}

{% if OUT.uart %}
HAL_StatusTypeDef OUT_UART_Print(const char *s);
{% endif %}

{% if OUT.pwm %}
void PWM_Set(uint16_t duty_0_1000);
{% endif %}

{% if OUT.dout %}
void DOUT_Write(GPIO_TypeDef *port, uint16_t pin, GPIO_PinState s);
{% endif %}

#ifdef __cplusplus
}
#endif
#endif /* __PRESETS_OUT_H__ */
