/**
  ******************************************************************************
  * @file           : uart.h
  * @brief          : Header for uart.c file. Contains UART/USART peripheral configurations.
  * @date           : {{ now().strftime('%b %d, %Y') }}
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */
/* Define to prevent recursive inclusion -------------------------------------*/
#ifndef __USART_H__
#define __USART_H__

#ifdef __cplusplus
extern "C" {
#endif

/* Includes ------------------------------------------------------------------*/
#include "main.h"


// --- Handles Declaration ---
{% for uart in uart_interfaces %}
extern UART_HandleTypeDef huart{{ uart.num }};
{% endfor %}

/* --- Function Prototypes --- */
void MX_UART_Init(void);

HAL_StatusTypeDef UART_Transmit(UART_HandleTypeDef *huart, uint8_t *data, uint16_t size, uint32_t timeout);
HAL_StatusTypeDef UART_Receive (UART_HandleTypeDef *huart, uint8_t *buffer, uint16_t size, uint32_t timeout);



#ifdef __cplusplus
}
#endif


