/**
  ******************************************************************************
  * @file           : gpio.h
  * @brief          : Header for gpio.c file. Contains GPIO pin configurations.
  * @date           : Nov 03, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#ifndef __GPIO_CONFIG_H__
#define __GPIO_CONFIG_H__

#include "stm32g4xx_hal.h"

#ifdef __cplusplus
extern "C" {
#endif

void MX_GPIO_Init(void);

#ifdef __cplusplus
}
#endif

#endif /* __GPIO_CONFIG_H__ */