/**
  ******************************************************************************
  * @file           : i2c.h
  * @brief          : Header for i2c.c file. Contains I2C peripheral configurations.
  * @date           : Oct 30, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#ifndef __I2C_H__
#define __I2C_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

/* --- I2C Handles (Extern Declaration) --- */
extern I2C_HandleTypeDef hi2c1;

/* --- I2C Slave Device Addresses --- */
/* Slave Addresses for I2C1 Bus */
#define GY521_MPU6050_ADDR (0xD0) 
#define LCD_PCF8574_ADDR (0x4E) 

/* --- Function Prototypes --- */
void MX_I2C_Init(void);

/* --- Application-level Functions --- */
HAL_StatusTypeDef I2C_Write(I2C_HandleTypeDef *hi2c, uint16_t dev_address, uint8_t *data, uint16_t size);
HAL_StatusTypeDef I2C_Read(I2C_HandleTypeDef *hi2c, uint16_t dev_address, uint8_t *buffer, uint16_t size);
HAL_StatusTypeDef I2C_Read_Register(I2C_HandleTypeDef *hi2c, uint16_t dev_address, uint8_t reg_address, uint8_t *buffer);
HAL_StatusTypeDef I2C_Write_Register(I2C_HandleTypeDef *hi2c, uint16_t dev_address, uint8_t reg_address, uint8_t value);


#ifdef __cplusplus
}
#endif
#endif /* __I2C_H__ */