/*
 * i2c.h
 *
 * Created on: Oct 26, 2025
 * Author: Auto-generated by Config Tool
 */

#ifndef __I2C_H__
#define __I2C_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

/* --- I2C Handles (Extern Declaration) --- */
extern I2C_HandleTypeDef hi2c1;
extern I2C_HandleTypeDef hi2c2;

/* --- I2C Slave Device Addresses --- */

/* --- Function Prototypes --- */
void MX_I2C_Init(void);

/* --- Application-level Functions --- */
HAL_StatusTypeDef I2C_Write(I2C_HandleTypeDef *hi2c, uint16_t dev_address, uint8_t *data, uint16_t size);
HAL_StatusTypeDef I2C_Read(I2C_HandleTypeDef *hi2c, uint16_t dev_address, uint8_t *buffer, uint16_t size);
HAL_StatusTypeDef I2C_Read_Register(I2C_HandleTypeDef *hi2c, uint16_t dev_address, uint8_t reg_address, uint8_t *buffer);
HAL_StatusTypeDef I2C_Write_Register(I2C_HandleTypeDef *hi2c, uint16_t dev_address, uint8_t reg_address, uint8_t value);


#ifdef __cplusplus
}
#endif
#endif /* __I2C_H__ */