/*
 * i2c.h
 *
 * Created on: Oct 08, 2025
 * Author: Auto-generated by Config Tool
 */

#ifndef __I2C_H__
#define __I2C_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"

/* --- I2C Handles (Extern Declaration) --- */
extern I2C_HandleTypeDef hi2c1;

/* --- I2C Slave Device Addresses --- */
/* Slave Addresses for I2C1 Bus */
#define TEMP_SENSOR_ADDR (0x94) // O valor já vem calculado de Python

/* --- Function Prototypes --- */
void MX_I2C_Init(void);


#ifdef __cplusplus
}
#endif
#endif /* __I2C_H__ */