/**
  ******************************************************************************
  * @file           : presets_in.h
  * @brief          : Header for presets_in.c file. Contains preset input sensor function prototypes.
  * @date           : Nov 03, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#ifndef __PRESETS_IN_H__
#define __PRESETS_IN_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"
#include "stm32g4xx_hal_adc.h"





/* ADC helpers for analog sensors */
HAL_StatusTypeDef ADC_Read_Channel(ADC_HandleTypeDef *hadc, uint32_t channel, uint16_t *raw);

/* Potentiometer ADC functions */
HAL_StatusTypeDef POT_ReadRaw(ADC_HandleTypeDef* hadc, uint32_t channel, uint16_t* out_raw);
float POT_RawToRatio(uint16_t raw);

#ifdef __cplusplus
}
#endif
#endif /* __PRESETS_IN_H__ */