/**
  ******************************************************************************
  * @file           : presets_in.h
  * @brief          : Header for presets_in.c file. Contains preset input sensor function prototypes.
  * @date           : Oct 30, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#ifndef __PRESETS_IN_H__
#define __PRESETS_IN_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"
#include "i2c.h"


/* GY-521 / MPU6050 */
void MPU6050_Init(void);
void MPU6050_Read_Accel(float *ax, float *ay, float *az);
void MPU6050_Read_Gyro(float *gx, float *gy, float *gz);




#ifdef __cplusplus
}
#endif
#endif /* __PRESETS_IN_H__ */