/**
  ******************************************************************************
  * @file           : presets_out.h
  * @brief          : Header for presets_out.c file. Contains preset output actuator function prototypes.
  * @date           : Nov 03, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#ifndef __PRESETS_OUT_H__
#define __PRESETS_OUT_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"
#include "uart.h"


HAL_StatusTypeDef OUT_UART_Print(const char *s);



#ifdef __cplusplus
}
#endif
#endif /* __PRESETS_OUT_H__ */