/**
  ******************************************************************************
  * @file           : presets_out.h
  * @brief          : Header for presets_out.c file. Contains preset output actuator function prototypes.
  * @date           : Oct 30, 2025
  * @author         : Auto-generated by Config Tool
  ******************************************************************************
  */

#ifndef __PRESETS_OUT_H__
#define __PRESETS_OUT_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "main.h"
#include "i2c.h"

void LCD_Init(void);
void LCD_Clear(void);
void LCD_SendString(const char *s);
void LCD_SetCursor(uint8_t row, uint8_t col);




#ifdef __cplusplus
}
#endif
#endif /* __PRESETS_OUT_H__ */